[package]
name = "decisionengine"
version = "0.1.0"
authors = ["Samuel Wong <samuel.wong@pay4later.com>"]

[dependencies]
serde = "1.0.66"
serde_derive = "1.0.71"
serde_json = "1.0"
regex = "1"
clap = "2"